plugins {
    kotlin("jvm") version "2.0.20"
}

group = "org.example"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(kotlin("test"))
}

tasks.test {
    useJUnitPlatform()
}
kotlin {
    jvmToolchain(21)
}

tasks.register("generateIndex") {
    val problemsDir = layout.projectDirectory.dir("src/main/kotlin/problems")
    val indexFile = layout.projectDirectory.file("README.md")
    inputs.dir(problemsDir)
    outputs.file(indexFile)
    doLast {
        val notesFiles = problemsDir.asFile.listFiles()
            ?.filter { it.isDirectory && it.resolve("Notes.md").exists() }
            ?.sortedBy { it.name }
            ?: emptyList()

        data class Problem(val packageName: String, val title: String, val neetcode: String, val leetcode: String)

        val problems = notesFiles.map { dir ->
            val raw = dir.resolve("Notes.md").readText()
            val fm = Regex("""^---\n(.*?)\n---\n""", setOf(RegexOption.DOT_MATCHES_ALL))
                .find(raw)?.groupValues?.get(1).orEmpty()
            fun field(name: String): String =
                Regex("""$name:\s*(.+)""").find(fm)?.groupValues?.get(1)?.trim().orEmpty()
            Problem(
                packageName = dir.name,
                title = field("title").ifEmpty { dir.name },
                neetcode = field("neetcode"),
                leetcode = field("leetcode"),
            )
        }

        val rows = problems.mapIndexed { i, p ->
            "| ${i + 1} | ${p.title} | ${p.neetcode} | ${p.leetcode} | `problems.${p.packageName}` |"
        }.joinToString("\n")

        indexFile.asFile.writeText(
            """
            |# NeetCode 250 Solutions
            |
            || # | Problem | NeetCode | LeetCode | Package |
            ||---|---------|:--------:|:--------:|---------|
            |$rows
            |
            |_Auto-generated by the `generateIndex` Gradle task — do not edit by hand._
            |
            """.trimMargin()
        )
        println("Regenerated README.md with ${problems.size} problem(s).")
    }
}